locale: en_us
translation:
  tl.cmd:
    root:
      usg: <command> sub-command args
      permMsg: ""
    reload:
      desc: reload templates, wordStocks and translation files
      usg: <command>
      permMsg: ""
      reloading_cfg: reloading templates and wordStocks...
      reloading_lapi: reloading translation files...
      reload_finish: reload finished
    get:
      desc: generate an template item to the player
      usg: <command> [group] <template> [player] [key1 value1 key2 value2 ...]
      permMsg: ""
      offline_player: "Can give the item to an offline player: <player>"
      parse_success: "Item has sent to player <player>"
      not_exist: "Can find template <name> in group <group>"
    list:
      desc: list all available templates
      usg: <command> [group] [page]
      permMsg: ""
      page_not_num: <arg> is not a number
      list_title: "Available templates in <group> at page <page>: "
