name: TemplateLore
version: ${version}
main: com.github.mrmks.mc.template.TemplateLore
depend: [LibMarcaBone]
softdepend: [PlaceholderAPI]
commands:
  tl:
    description: base command of template lore
permissions:
  tl.perm.cmd.give:
    default: op
  tl.perm.cmd.list:
    default: op
  tl.perm.cmd.reload:
    default: op
  tl.perm.cmd.*:
    default: op
    children: [tl.perm.cmd.give, tl.perm.cmd.list, tl.perm.cmd.reload]