name: TemplateLore
version: ${version}
main: com.github.MrMks.template_lore.Main
depend: [DevToolsB]
softdepend: [PlaceholderAPI]
commands:
  tl:
    permission: tl.perm.*
permissions:
  tl.perm.get:
    default: op
  tl.perm.list:
    default: op
  tl.perm.reload:
    default: op
  tl.perm.*:
    default: op
    children: [tl.perm.get, tl.perm.list, tl.perm.reload]